language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
install:
  - cpan-install --deps
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
