language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "blead"
matrix:
  include:
    - perl: 5.18.2
      env: COVERAGE=1
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
install:
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
after_success:
  - coverage-report
